### ISSUE TITLE
docker运行日志显示 bind '0.0.0.0:80': Permission denied

### ISSUE THREAD

**Issue by zulan88** [illacloud/illa-builder#1045]
### Description

illa_builder容器运行时日志打印bind '0.0.0.0:80': Permission denied

### Steps to reproduce

使用cargo install illa 安装

illa doctor
🔍  Checking the prerequisites of self-host...
✅  Docker version: 23.0.1
✨  Success! The minimum requirement for deploying ILLA has been satisfied. Self-Host your ILLA Builder by command [illa deploy].  

输入illa deploy --self --port=10000命令快速部署
发现网页无法访问
检测端口10000监听正常

docker logs illa_builder
发现日志
[2023-03-03 02:49:45.743][93][critical][main] [source/server/server.cc:113] error initializing configuration '/opt/illa/envoy/illa-unit-ingress.yaml': cannot bind '0.0.0.0:80': Permission denied
[2023-03-03 02:49:45.744][93][info][main] [source/server/server.cc:815] exiting
cannot bind '0.0.0.0:80': Permission denied

### ILLA Builder Version

1.2.8

### Browser

Google Chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by zulan88** [comment]
关闭selinux也不能解决这个问题

**Comment by zulan88** [comment]
是用docker命令启动可避开80端口绑定的问题，_似乎可以使用_
docker命令如下
docker run --name=illa_builder  --env=ILLA_SERVER_MODE=release --env=ILLA_DEPLOY_MODE=self-host --env=POSTGRES_PASSWORD=fc66fe49-a049-4032-8660-d84efad181dc --env=API_SERVER_ADDRESS=localhost --env=WEBSOCKET_SERVER_ADDRESS=10.102.1.112 -p 5432:5432 -p 10000:10000  --label='license=Apache-2.0' --label='maintainer=opensource@illasoft.com' --runtime=runc --detach=true -v /root/illa-unit-ingress.yaml:/opt/illa/envoy/illa-unit-ingress.yaml illasoft/illa-builder:latest /usr/bin/dumb-init -- /opt/illa/main.sh

**Comment by yusp998** [comment]
> ### Description
> illa_builder容器运行时日志打印bind '0.0.0.0:80': Permission denied
> 
> ### Steps to reproduce
> 使用cargo install illa 安装
> 
> illa doctor 🔍 Checking the prerequisites of self-host... ✅ Docker version: 23.0.1 ✨ Success! The minimum requirement for deploying ILLA has been satisfied. Self-Host your ILLA Builder by command [illa deploy].
> 
> 输入illa deploy --self --port=10000命令快速部署 发现网页无法访问 检测端口10000监听正常
> 
> docker logs illa_builder 发现日志 [2023-03-03 02:49:45.743][93][critical][main] [source/server/server.cc:113] error initializing configuration '/opt/illa/envoy/illa-unit-ingress.yaml': cannot bind '0.0.0.0:80': Permission denied [2023-03-03 02:49:45.744][93][info][main] [source/server/server.cc:815] exiting cannot bind '0.0.0.0:80': Permission denied
> 
> ### ILLA Builder Version
> 1.2.8
> 
> ### Browser
> Google Chrome
> 
> ### Operating System
> * [ ]  macOS
> * [ ]  Windows
> * [x]  Linux
> 
> ### Additional Information
> _No response_

同样的问题，请问怎么解决啊，docker命令也不行

**Comment by zulan88** [comment]
@yusp998 我改了配置文件的端口，你使用docker命令要根据你的情况修改

**Comment by Qi-Zou** [comment]
还有其他的解决办法吗？或者说哪个docker命令是否可以详细说明一下不？

**Comment by karminski** [comment]
@zulan88 @Qi-Zou @yusp998 Hi, 我们已经更新了新的镜像, envoy 将使用容器内 root用户启动, 方便使用well-known port. 
请拉取最新镜像:
```
docker pull illasoft/illa-builder:latest
````

**Comment by donqu1xotechina** [comment]
hey:
如果您有更进一步的问题，可以移步我们的Discord社群获取快捷的技术支持哦！
邀请链接如下：
https://discord.com/invite/illacloud
