### ISSUE TITLE
无法拖动组件到页面上，看日志报错response: null, err: <nil>token:

### ISSUE THREAD

**Issue by yusp998** [illacloud/illa-builder#1078]
### Description

无法拖动组件到页面上

### Steps to reproduce

1. 拖动组件到页面（无效）
2. docker logs illa-builder
3. See error：err: <nil>
response: null, err: <nil>token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJ1dWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwicm5kIjoiMDA0MTU3IiwiaXNzIjoiSUxMQSIsImV4cCI6MTY3ODg1NjQwMX0.gP6wG3JVSCyOMt1GJZbcpf-hERqCnoCW5g-A-4AAjr0
errInValidate: <nil>

### ILLA Builder Version

1.9.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![1678254069798](https://user-images.githubusercontent.com/126861196/223628951-d03433f3-56d8-425a-bc42-b71273d57156.png)

**Comment by donqu1xotechina** [comment]
Hey
我们会尽快修复这个问题。
方便移步我们Discord社区获取更及时的技术支持吗？
社区链接： https://discord.com/invite/illacloud

ILLA Team
