### ISSUE TITLE
为什么资源输入完mysql之类的连接参数之后，下面的按钮还是灰色的呢？无法点击

### ISSUE THREAD

**Issue by shiliu2023** [illacloud/illa-builder#1127]
### Description

为什么资源输入完mysql之类的连接参数之后，下面的按钮还是灰色的呢？无法点击。那个test测试连接的按钮也无法点击。

### Steps to reproduce

为什么资源输入完mysql之类的连接参数之后，下面的按钮还是灰色的呢？无法点击。那个test测试连接的按钮也无法点击。

### ILLA Builder Version

1.0

### Browser

chrome

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

为什么资源输入完mysql之类的连接参数之后，下面的按钮还是灰色的呢？无法点击。那个test测试连接的按钮也无法点击。

**Comment by shandamengcheng** [comment]
> 
您好，按钮为灰色表示仍有必填项没有输入，请您看一下是否有数据输入的遗漏。此外，如果方便的话，麻烦您放一张配置截图以便于快速排查问题。谢谢！

**Comment by shiliu2023** [comment]
都输入完了啊，我发个截图。截图如下：
![image](https://user-images.githubusercontent.com/127192842/225469534-1d8e8da0-50e2-493a-ad5d-659e82f6fa39.png)

**Comment by shiliu2023** [comment]
本来还以为是需要root登录，但是root登录也不行😂

**Comment by shiliu2023** [comment]
感觉这个按钮灰色真没有什么作用，多此一举。还不如在提交的时候触发得了

**Comment by shiliu2023** [comment]
我天啦，我明白了，哈哈哈哈哈。你还不如直接黑色默认。😂
