### ISSUE TITLE
javascript transformer can't execute basic js functions

### ISSUE THREAD

**Issue by recursively** [illacloud/illa-builder#1230]
### Description

transformer is too weak to execute js code

### Steps to reproduce

the transformer is too weak to execute js code, and even cannot convert a float-like string to a real float number, e.g. convert "0.6" to 0.6, parseFloat function is not working at all. In this case, it's impossible to do any numeric calculation with the user's input because the user's input is always a string value. It's kidding me.

### ILLA Builder Version

2.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by AruSeito** [comment]
Hello, the code sandbox is currently being optimized and is expected to be launched in the near future.

**Comment by recursively** [comment]
> Hello, the code sandbox is currently being optimized and is expected to be launched in the near future.

Great to hear that, looking forward to the updates as soon as possible, it's definitely a pain in the ass for the current javascript transformer.

**Comment by tonypius** [comment]
I'm having the same issue. Transformers are not executing any js code. When will this be fixed ?

**Comment by AruSeito** [comment]
> I'm having the same issue. Transformers are not executing any js code. When will this be fixed ?

hello，We will release the next version, which is expected to be released next Thursday.

**Comment by AruSeito** [comment]
Hello, @tonypius @recursively 
We just released a fixed version, you can try again

**Comment by AruSeito** [comment]
We have fixed the bug, but have not received your response for a long time. We will close the issue for processing. If you have any questions, you can open the issue again
