### ISSUE TITLE
illa deploy --server-addr doesnt exist

### ISSUE THREAD

**Issue by tonypius** [illacloud/illa-builder#1377]
### Description

when i tried the illa deploy command with server-addr option its failing

### Steps to reproduce

1. Command i'm running  ./illa deploy --self --port=3000 --server-addr=xx.xx.xx.xx --mount=/illa-x86_64-linux/tmp/illa-builder
2. Error i'm getting is "error: unexpected argument '--server-addr' found"
3

What I want is to access the illa builder on a domain i've configured and reverse proxy setup on nginx. DNS record is in place and nginx reverse proxy is pointing to the http://localhost:3000

What should I do ?

### ILLA Builder Version

1.2.9

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by AruSeito** [comment]
Hello,"--server-addr" is removed,we'll update documents later

**Comment by tonypius** [comment]
Is there any way I can make the illa-builder accessible on a SSL domain ?

**Comment by karminski** [comment]
@tonypius hi, you can add a reverse proxy (like nginx or envoy) for illa-builder and config your SSL certificate in it. Here is an sample config: https://github.com/illacloud/deploy-illa-manually/blob/main/kubernetes/README.md#for-https-config
