### ISSUE TITLE
ClickHouse connect error

### ISSUE THREAD

**Issue by lxzhh** [illacloud/illa-builder#1665]
### Description

when I use illa to connect to our ClickHouse server, got error 'tls: first record does not look like a TLS handshake'

### Steps to reproduce

1. Go to 'Resources' tab
2. Click on 'Create New'
3. Select ClickHouse
4. Add the server IP to ClichHouse WhiteList
5. fill the connect form as in the screenshot

By the way, we use another retool like low-code system in the same server, and we use the same connect to our ClickHouse and it works well

### ILLA Builder Version

illa 1.2.10

### Browser

Google Chrome 113.0.5672.126

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![20230524-152333](https://github.com/illacloud/illa-builder/assets/1468557/3098a95e-6a60-4e69-b998-dab6aa98dd81)

**Comment by naj1n** [comment]
Thanks for your issue, it's a bug. We'll fix it ASAP.

**Comment by naj1n** [comment]
We have addressed this issue in the latest version release(illa-builder@2.5.0). Please update to the newest version and check if the problem has been resolved. Let us know if you have any other questions or concerns.

**Comment by lxzhh** [comment]
> 

Thanks for the quick fix. But we've checked, this time we get a new error :`test connection failed: [handshake] unexpected packet [72] from server` when we test the connector.

**Comment by naj1n** [comment]
ILLA Builder is using the `native` interface to connect to ClickHouse, so we recommend using port `9000`. ILLA Builder is not using port `8123` because the HTTP interface connection feature of [clickhouse-go](https://github.com/ClickHouse/clickhouse-go) is still in the `Experimental` stage. If you need to connect using port 8123, feel free to file a feature request.

**Comment by lxzhh** [comment]
> port `9000` is fine, it works. Thank you @naj1n
