### ISSUE TITLE
Typo for PDF component's data "showToolBar"

### ISSUE THREAD

**Issue by JessicaHu03** [illacloud/illa-builder#1738]
### Description

When I type "pdf1.show", I expect to see "showToolBar" while it actually shows "showTollBar". I believe there's a typo.

### Steps to reproduce
![WRGvmjebdQ](https://github.com/illacloud/illa-builder/assets/52292735/6ade6262-50b4-4662-a05a-efbb7f9499f2)

### ILLA Builder Version

2.6.2

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by alidotdeveloper** [comment]
Hello @AruSeito, if it's not fixed can I work on that?

**Comment by AruSeito** [comment]
@alidotdeveloper Yes！Glad you are interested in this question!We welcome anyone to fixed!

**Comment by ManishDait** [comment]
@AruSeito I would like to work on this Issue.
