### ISSUE TITLE
[Feature Request] Ctrl+z on canvas

### ISSUE THREAD

**Issue by JessicaHu03** [illacloud/illa-builder#1752]
### Description

When I accidentally delete my container component, I expected to get it back by pressing ctrl+z, but it does not work. Ctrl+z works for input fields like "label", "data source" when configuring components but not on canvas.

### ILLA Builder Version

2.6.2

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
This feature has been launched on 2.8.x
