### ISSUE TITLE
Viewer level user cannot trigger query event

### ISSUE THREAD

**Issue by hoshearose** [illacloud/illa-builder#1884]
### Description

When I interact with a self hosted app as a viewer some action are not working

### Steps to reproduce

Create self hosted app
add input field to triggers db query with field value as query parameter
deploy app  (private)
log in as a viewer user (can use incognito browser) 
try to input parameter
expected:
table returns data
actual:
no data in table
an 

### ILLA Builder Version

self hosted, deployed alst week

### Browser

chrome latest

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

discussed, debugged and fixed already via discord chat!
![image](https://github.com/illacloud/illa-builder/assets/63545528/66bae6b6-b764-4f10-8911-62f96ca1568e)
![image](https://github.com/illacloud/illa-builder/assets/63545528/e336cae1-f8f4-4ed1-b2f0-74fb9523dabd)

**Comment by karminski** [comment]
@hoshearose Hi, It is a user role attribute issue. And we already fixed it. Please pull the latest docker image and have a try. 
```
docker pull illasoft/illa-builder:latest
```

**Comment by hoshearose** [comment]
checked and it works now, Thanks!
