### ISSUE TITLE
[Feature Request] More styling for table components

### ISSUE THREAD

**Issue by JessicaHu03** [illacloud/illa-builder#1897]
### Description

The table component is lacking style section. The table components does not go with my whole page styling and frustrates me. Can you add more style options to table components such as radius, outline color, different text color for the selected row and/or text font and text color for the header(column names)?)

### ILLA Builder Version

2.8.7

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by HabelStefan** [comment]
I agree!

**Comment by wenzhuo2022** [comment]
Thanks for your feedback. We have added it to our plan and may release the new feature next month.
