### ISSUE TITLE
Customize validation error messages

### ISSUE THREAD

**Issue by HabelStefan** [illacloud/illa-builder#1910]
### Description

When using the form validation, the integrated error messages are almost :) correct, but not very helpful for a user.

### Steps to reproduce

For example:

1. adding a text_input
2. set Min Length to {{1}}
3. click submit
4. The error message is "Must be greater than 1" which is not correct at all (i should be greater then 0 if min length is 1) and i would prefer a message like "Must not be empty.

### ILLA Builder Version

2.8.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by wenzhuo2022** [comment]
Thanks for your feedback. You can customize the message. For example:
![image](https://github.com/illacloud/illa-builder/assets/112603073/0d859921-9a04-4801-9518-fe3cca1af831)
