### ISSUE TITLE
Search functionality for component selection

### ISSUE THREAD

**Issue by StefanDorschu** [illacloud/illa-builder#1915]
### Description

Using long component name scheme makes it impossible to distinguish the component when selecting.

### Steps to reproduce

I'm using quite an extensive naming for my components like pagename_view_componenttype_name.

When trying to select these components in an event, its hardly possible at all because only some parts of the name are shown.

What we need is

1. Search functionality to filter a lot of components
2. Resizable selection window to view the full name

### ILLA Builder Version

2.8.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="402" alt="Bildschirmfoto 2023-07-20 um 09 31 49" src="https://github.com/illacloud/illa-builder/assets/24601959/81e8e41e-496b-4322-b89b-49b8e5d7c74a">

**Comment by AruSeito** [comment]
This feature will be launched today

**Comment by AruSeito** [comment]
Hello,
This feature (Search functionality to filter a lot of components) is launched

**Comment by HabelStefan** [comment]
Thanks for the update.

Although i can search for the components now, it's not very convenient as i can limit the components shown but still have no chance to distinguish between each of them as the listing has a fixed size. 

Making this resizable would be a huge improvement.

**Comment by AruSeito** [comment]
Yes, we will optimize for this situation in the future, but currently, due to code architecture limitations, it is difficult for us to have him support resizable

**Comment by HabelStefan** [comment]
Would a quick solution adding a tooltip that shows the full name?

**Comment by AruSeito** [comment]
This is a great suggestion. I will try to modify it.

**Comment by AruSeito** [comment]
This is a great suggestion. I will try to modify it.
