### ISSUE TITLE
Docker Container with tag:lastest is not the highest version number

### ISSUE THREAD

**Issue by StefanDorschu** [illacloud/illa-builder#1918]
### Description

When pulling docker tag:lastest i get 2.8.4, while there is a 2.8.7 available

### Steps to reproduce

Is this still the newest version or is it 3 version behind 2.8.7?

### ILLA Builder Version

2.8.4

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
plz pull latest.We will improve the use of version numbers in the future.now you can pull 2.9.1
