### ISSUE TITLE
点击按钮触发API请求，将API返回的数据设置到其他组件时，设置的数据不是本次返回的数据，而是上次请求返回的数据

### ISSUE THREAD

**Issue by zhaoyaohui0** [illacloud/illa-builder#1924]
### Description

点击按钮触发API请求，将API返回的数据设置到其他组件时，设置的数据不是本次返回的数据，而是上次请求返回的数据

### Steps to reproduce

![image](https://github.com/illacloud/illa-builder/assets/123867133/e04fe2f6-715a-4c22-8ccc-ac1a32f409ea)
![image](https://github.com/illacloud/illa-builder/assets/123867133/d7312fd9-7187-4645-8f85-f0a5f47f182b)
![image](https://github.com/illacloud/illa-builder/assets/123867133/6dbbf415-3465-4119-8fa5-1d8209a07d0b)
![image](https://github.com/illacloud/illa-builder/assets/123867133/ad093451-2661-4924-b466-1376cbef6d3f)

### ILLA Builder Version

2.8.7

### Browser

Google Chrome 114.0.5735.201

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
您好，今晚会发布新版本，将在新版本修复。

**Comment by AruSeito** [comment]
您好，该修复已发布
