### ISSUE TITLE
Statistic component not vertically resizable

### ISSUE THREAD

**Issue by HabelStefan** [illacloud/illa-builder#1959]
### Description

I can not resize the height of the statistic component.

### Steps to reproduce

I added a statistic component. Although it shows vertical scrollbars i can not adjust the height!
<img width="256" alt="statisticcomponent" src="https://github.com/illacloud/illa-builder/assets/24601959/d702e41f-e5de-4d4c-9dd6-1244a53c0d01">

### ILLA Builder Version

2.9.5.

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
We solved it.To be released in the next version
Thanks for your feedback
