### ISSUE TITLE
[Feature Requested] Share options for deployed app

### ISSUE THREAD

**Issue by JessicaHu03** [illacloud/illa-builder#1969]
After I created an app in ILLA Builder, I would like to share it with my friends and maybe post it on the internet. However, rather than copy-paste a link or have people click the link to jump to the deployed app. I wonder if I can have it embedded in a small window on my website or in my blog so my viewers and/or readers can try and demo the app I build out. Can you provide me with that embed code?

**Comment by wenzhuo2022** [comment]
Hello, thanks for your feedback. Here is the HTML code. Change the link to your app and make sure your app is public
<iframe src="https://www.illacloud.com" style="border:none; width:100%; height:500px;"></iframe>
