### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ssfufu** [illacloud/illa-builder#1981]
### Description

"Network disconnected. Please check the network of this device." when creating an app when using HTTPS.

### Steps to reproduce

1. Get a Debian 11 instance (in my case, a VPS)
2. Install Rust and Illa CLI and build-essential.
```shell
apt-get install build-essential
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
cargo install illa
illa doctor
``` 

4. Deploy with `illa deploy --self --port=2022` or any port.
5. Apply a reverse proxy configuration with nginx (see the code below) with HTTPS enabled.
6. Go to the site using the domain, create an account, and log in.
7. Create an app. At this point I have the issue as seen in this [picture](https://drive.google.com/file/d/1ybAHvONZT3nLmMpcmH72giEPCzTMglV-/view?usp=sharing).

This is the reverse proxy configuration I use.
```
server {
    server_name illa.domain.com;
    location / {
        allow all;
        proxy_pass http://127.0.0.1:2022;
        proxy_set_header Host illa.domain.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Accel-Buffering no;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection '';
        proxy_redirect http://127.0.0.1:2022 https://illa.domain.com;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/illa.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/illa.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = illa.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    # sub.domain.dom
    server_name illa.domain.com;
    return 404; # managed by Certbot
}
``` 

### Version

self-host

### ILLA Builder Version

2.9.6

### Browser

Mozilla Firefox and Google Chrome (both latest on the 28th July 2023)

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

#### The issue is still valid when using the binaries directly.

**Comment by karminski** [comment]
@ssfufu Hi, Thanks for the issue, I'll try to reproduction this case and feedback later.

**Comment by ssfufu** [comment]
### Update:

I have read the logs of the docker container. It was written at some point:
`[illa-builder-backend-ws]  2023/07/29 15:29:12 Not a web socket connection: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header`

So it was a mistake I made. Sorry for the inconvenience.

**Here is the fix:**
I went from using, in my nginx config: `proxy_set_header Connection '';`
To, the correct line: `proxy_set_header Connection "upgrade";`

**Comment by karminski** [comment]
@ssfufu Glad to hear it, Greate job!
