### ISSUE TITLE
Datetime library

### ISSUE THREAD

**Issue by ezcell** [illacloud/illa-builder#1993]
Can we add a datetime library like momentjs? That would help with our app, our users cover a bunch of timezones.

**Comment by wenzhuo2022** [comment]
Hello, thanks for using ILLA. We will support this feature in the next two weeks and will let you know when it is launched.

**Comment by wenzhuo2022** [comment]
Sorry, I just confirmed with the engineer. Currently, we support dayjs, and you can use dayjs to solve your problem. There are no plans to support momentjs at the moment.

**Comment by ezcell** [comment]
Oh ya that would work just fine.
Do you have a list of libraries that are supported with illacloud?

**Comment by wenzhuo2022** [comment]
Sure, we currently support these libraries: lodash, uuid, numbro, dayjs. If you have any other libraries you need support for, please feel free to provide us with your feedback.
