### ISSUE TITLE
[Feature Requested] Flexible Transformer Javascript area

### ISSUE THREAD

**Issue by JessicaHu03** [illacloud/illa-builder#2053]
When I use the transformer function in the bottom of a resource, the window of me typing my js code is too short. I have to keep scrolling up and down to see my code, which is very uncomfortable to use.
Can you make it a flexible height limit?

**Comment by wenzhuo2022** [comment]
Hello, you can click and drag the resize button to adjust it. 
![image](https://github.com/illacloud/illa-builder/assets/112603073/e3bcc601-54da-46ae-adbd-e19b78b8f56f)
![image](https://github.com/illacloud/illa-builder/assets/112603073/e5f0e5fb-dabb-4c0c-a802-3632188f4554)
