### ISSUE TITLE
[BUG] Incorrect data display format

### ISSUE THREAD

**Issue by alili** [illacloud/illa-builder#2075]
### Description

I want to show a decimal with two digits reserved in the mapped value, but identified as a time format

### Steps to reproduce

1. create a table
2. set Column type `Auto`
3. set Mapped Value like `{{(currentRow.coin/currentRow.view  * 100).toFixed(2) }}%`

![image](https://github.com/illacloud/illa-builder/assets/4102907/99da49db-da0f-490a-ae67-31dc0bf81188)

### Version

cloud

### ILLA Builder Version

cloud

### Browser

chrome 116

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
Hello，Thanks for your feedback，we'll fix it soon

**Comment by AruSeito** [comment]
Hello,we fixed it. plz check it again
