### ISSUE TITLE
[Feature Requested] Visible or invisible table fields can be represented by different icons

### ISSUE THREAD

**Issue by alili** [illacloud/illa-builder#2076]
![image](https://github.com/illacloud/illa-builder/assets/4102907/9be5611c-d644-4390-ae68-8196e9f3ecff)

**Comment by AruSeito** [comment]
Hello, I think your suggestion is very good. We will replace ICON in the next version

**Comment by rakzool** [comment]
Hi @AruSeito  , i would like to work on this feature , if no one is woking on this already
