### ISSUE TITLE
[BUG] When adding an event handler to the action, the modal popup position is incorrect.

### ISSUE THREAD

**Issue by wenzhuo2022** [illacloud/illa-builder#2090]
### Description

When adding an event handler to the action, the modal popup position is incorrect. 

### Steps to reproduce

1. Go to 'App editor page'
2. Close the left panel：
<img width="832" alt="image" src="https://github.com/illacloud/illa-builder/assets/112603073/c9bb7648-ccd6-478e-b9dd-d1eaac744281">
3. Add an Action
4. Add an event handler to the action:
<img width="1233" alt="image" src="https://github.com/illacloud/illa-builder/assets/112603073/065adb03-5535-4e8b-90e7-ad846d35dc14">
5. Click the event handler to edit it:
<img width="1543" alt="image" src="https://github.com/illacloud/illa-builder/assets/112603073/afd24ad8-9bbf-45db-b48d-daf71954ff66">
7. See error. 

Expect: this modal expands above the event handler so that the popup content is fully visible.

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by ManishDait** [comment]
@wenzhuo2022 I would like to wok on these issue.

**Comment by anish-patro** [comment]
@wenzhuo2022 i would like to work on this issue as my first contribution to this repository, can you please assign it to me?

**Comment by AruSeito** [comment]
@anish-patro 
Hello,this issue is processing
