### ISSUE TITLE
[BUG] The component order is incorrect when pasting components

### ISSUE THREAD

**Issue by wenzhuo2022** [illacloud/illa-builder#2091]
### Description

The component order is incorrect when pasting components

### Steps to reproduce

1. put some text components on canvas: 
![image](https://github.com/illacloud/illa-builder/assets/112603073/69887eda-738d-49c0-9f13-71bcce3a62c4)
2. insert an image component: 
![image](https://github.com/illacloud/illa-builder/assets/112603073/21781f1d-aa4b-4f73-adde-db8cbda58eb1)
3. Copy the image component > select the first text and paste
before pasting:
![image](https://github.com/illacloud/illa-builder/assets/112603073/5afaa07f-5868-45cf-a7b9-97f58011465c)
after pasting: 
![image](https://github.com/illacloud/illa-builder/assets/112603073/54584896-4976-4cda-8fa4-fbe86c89d54a)

5. See error, the order of the components is wrong. 

Expect: The components below are being pushed down together without changing the component order.

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by mr-loop-1** [comment]
Hi, I want to work on this issue

**Comment by Akshaybagai52** [comment]
If he unable to do this then you can assign to me @AruSeito

**Comment by mr-loop-1** [comment]
Hi, @wenzhuo2022 @AruSeito 
I set the builder locally today and inspected this behavior. I find that the components are not being pasted according to any order but instead identical to their relative position on the canvas. For example,
**In both cases I am selecting Box 2 and then Box 1**

Case 1: Current Implementation
![Screenshot from 2023-10-02 17-11-01](https://github.com/illacloud/illa-builder/assets/62374784/36debdcc-c526-4345-8096-eac63075bbf4)

Case 2: Probably Intended
![Screenshot from 2023-10-02 17-11-39](https://github.com/illacloud/illa-builder/assets/62374784/928b0cff-03d4-4047-a658-b581b14e229b)

For the kind of application Illa Builder is, I believe that the current implementation is better suited when moving across. If we preserve the order of selection, we would probably have to stack them vertically.
Would appreciate your comments before continuing.

**Comment by mr-loop-1** [comment]
Hi @AruSeito , I would be unassigning myself from the issue. I believe that the existing logic is a core functioning component (and may even not be dropped after review) and I may not have the time commitment to do the changes required.

**Comment by AruSeito** [comment]
@Akshaybagai52 
Hello,Can you solve this?
