### ISSUE TITLE
Using a new resource resets all actions (queries)

### ISSUE THREAD

**Issue by StefanDorschu** [illacloud/illa-builder#2093]
### Description

Using a new resource resets all actions (queries)

### Steps to reproduce

1. Create a new resource (e.g. a backup database or a delopment database)
2. Change the resource for your actions.
3. All queries within these actions are gone
4. Reverting back to the old resource does not bring back the queries

### Version

cloud

### ILLA Builder Version

3.0.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
Thank you for your feedback. I will check it out
