### ISSUE TITLE
[BUG] When dragging a container-type component from the canvas body to the left panel, the internal components within the container are not properly adjusted, resulting in incomplete display.

### ISSUE THREAD

**Issue by wenzhuo2022** [illacloud/illa-builder#2094]
### Description

When dragging a container-type component from the canvas body to the left panel, the internal components within the container are not properly adjusted, resulting in incomplete display.

### Steps to reproduce

When dragging a container-type component from the canvas body to the left panel, the internal components within the container are not properly adjusted, resulting in an incomplete display. 

Expect：Convert component size based on column number, round up

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Vishalk91-4** [comment]
@wenzhuo2022 could you please assign this issue to me

**Comment by AruSeito** [comment]
fixed
