### ISSUE TITLE
[BUG] When using "Cmd+Z" or "Ctrl+Z" to undo, the height of the text component changes.

### ISSUE THREAD

**Issue by wenzhuo2022** [illacloud/illa-builder#2095]
### Description

When using "Cmd+Z" or "Ctrl+Z" to undo, the height of the text component changes.

### Steps to reproduce

Place a text component on the canvas and set it to auto height. Use a markdown level 1 heading for the text content, such as "# text". After performing other actions and then undoing them, the height of the text component is incorrect.

![20230915161341_rec_](https://github.com/illacloud/illa-builder/assets/112603073/9b60b844-38e6-4b68-bc3a-0245aa31508b)

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by MuhammadAakash** [comment]
Hi @wenzhuo2022. I would like to work on this issue. Can you please guide me on how should I set up the project? 
Thanks.

**Comment by AruSeito** [comment]
Hello @MuhammadAakash You can follow the instructions in this document for development

**Comment by MuhammadAakash** [comment]
@AruSeito Sorry, But which document?

**Comment by AruSeito** [comment]
@MuhammadAakash Mu
Sorry, my mistake.
Plz follow this document
https://github.com/illacloud/illa-builder/blob/beta/CONTRIBUTING.md

**Comment by MuhammadAakash** [comment]
@AruSeito .
Yeah I have followed this document and ai am getting above error. How should I solve it.

**Comment by MuhammadAakash** [comment]
Sure. I will do it again.

**Comment by SoNiC-HeRE** [comment]
Is this still open to work on?

**Comment by MuhammadAakash** [comment]
No, I am working on it.

**Comment by Mann-tech13** [comment]
Can I work on this issue?
Is it still open?

**Comment by MuhammadAakash** [comment]
@Mann-tech13 
I am working on it.

**Comment by AruSeito** [comment]
Fixed
