### ISSUE TITLE
MSSQL - SQL Injection

### ISSUE THREAD

**Issue by lukas-kd** [illacloud/illa-builder#2103]
### Description

When i tried out illa-builder and made a simple searchbox associated to filter within an action, i discovered that the statements will not bei prepared with parameters. So ist very easy to pass dangerous scripts. I know that this is for internal apps, but i would like to have security too.

### Steps to reproduce

1. Create a new text Input field
2. Create a simple query with a 'where name like {{input.value}}'
3. Add a event handler for 'Change' and trigger the action
4. Add a table with the data from the action
5. Deploy or preview the App
6. Type "' OR 1=1--" (Or other SQL injection things..)
7. And then you will see all Data

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It would be very nice and secure to prepare such statements. Maybe some other action providers have the same problem.

"Appsmith" can do prepare statements.

**Comment by karminski** [comment]
@lukaskuerzdoerfer Hi, the {{variableName}} statement will pass variable value directly. You can check user input manually. I think we can add a SQL filter or variable validator for this.  @wenzhuo2022

**Comment by lukaskuerzdoerfer** [comment]
@karminski how can i escapeSql within illa-builder?

Would be awesome to have this either checked or as a real prepared statement using parameters.

**Comment by lukas-kd** [comment]
@AaryaZ how can i assigne you this issue?

**Comment by lukas-kd** [comment]
You asked for the assignee of this issue. But i seem to not have the required rights for this task.

**Comment by AaryaZ** [comment]
So whom should I tag? Who is the maintainer?

**Comment by lukas-kd** [comment]
I think @AruSeito, but i dont know.

**Comment by AaryaZ** [comment]
@AruSeito can you plz assign me this issue so that I can completely focus on this issue and start working?

**Comment by AruSeito** [comment]
Hello， @AaryaZ We have begun to solve this. You can check other issues you are interested in. Or contact our relevant responsible personnel. @karminski

**Comment by karminski** [comment]
@lukas-kd @AaryaZ Hi, we have already finished implementing the SQL parameterized query method for this issue and are currently testing it on our test environment. We plan to release it this week. Once this feature is released, I will provide comments on this issue.

**Comment by karminski** [comment]
All the work has been completed on the backend service and does not require any changes to the current SQL in action.

**Comment by karminski** [comment]
@lukas-kd @AaryaZ  Hi, we have already released the new version! The new feature called "SQL Safe Mode" (it is a switch under the SQL text input).:
![image](https://github.com/illacloud/illa-builder/assets/1567626/2be3cbc4-6ea5-4659-a688-2212fd4a127c)
It is open by default when an action is created, and all SQL is parameterized when the switch is on (user input will be escaped).

The old action, by default, had this switch closed for maximal compatibility. So please manually switch it on if you have an old action.

Also, note that it is parameterized SQL, so keywords or operators cannot be used as parameters in the SQL.

For example, this is illegal in safe mode (using table name as a parameter):

```sql
SELECT * FROM {{input1.value}};  ❌
```

Parameter are fully supported in safe mode:

```sql
SELECT * from users where id = {{input1.value}} or uid = {{input2.value}}::uuid; ✅
```

It will be converted to this in the background by the SQL compiler:

```sql
SELECT * from users where id = $1 or uid = $2::uuid; ✅
```

String templates also work:

```sql
SELECT * from users where name like '%{{input1.value}}%'; ✅
```

It will be converted to this in the background by the SQL compiler:

```sql
SELECT * from users where name like CONCAT('%', $1, '%'); 
```

That's all! Please feel free to comment if you have any questions or suggestions here. 😄
