### ISSUE TITLE
[BUG] Images not loading in the readme.md file 

### ISSUE THREAD

**Issue by Debaditya-Som** [illacloud/illa-builder#2199]
### Description

When I was reading the README.md file, I expected to view the images  under "Get Stared " section  instead , there was no image found and error was thrown stating that there was no image

### Steps to reproduce

1. Go to 'READEME.md'
2. Scroll down to " Get Started'
3. See error

### Version

cloud

### ILLA Builder Version

1.0.0

### Browser

Google Chrome 93

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/illacloud/illa-builder/assets/121785700/de91d9a1-eb66-4c7b-b8de-7ff1fe012632)

As it is seen this in screenshot there was a problem in loading the image.

**Comment by Debaditya-Som** [comment]
If accepted, I would love to work on this issue

**Comment by AruSeito** [comment]
This may not be a bug?
I have tried changing network environments and devices, and they can display normally.

**Comment by Debaditya-Som** [comment]
@AruSeito Initially it wasn't loading that day, now after refreshing the page it still took few minutes to load.
