### ISSUE TITLE
Read-Only does not work for date-input component

### ISSUE THREAD

**Issue by StefanDorschu** [illacloud/illa-builder#2481]
### Description

I can still change the date although read-only is set to true

### Steps to reproduce

1. Add a date-input component
2. Set readonly to {{true}}
3. Preview the app
--> You can still edit the value of this field.

### Version

cloud

### ILLA Builder Version

most recent

### Browser

Arc

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ManishDait** [comment]
Hi @AruSeito,
I've reviewed the codebase and noticed that in the **DateWidget** class, the `onchange` method is being called even when the `editable` attribute is set to `false`. Therefore, I believe that adding a check for `readonly` in the function might be a solution.
I would like to work on this issue.

**Comment by donqu1xotechina** [comment]
Hey @ManishDait 
Apologies for the delay! You may work on this issue now!
Looking forward to your contribution!

**Comment by ManishDait** [comment]
Can you please review my PR:#2520
