### ISSUE TITLE
[ILLA Builder App] Github Stats Generator

### ISSUE THREAD

**Issue by Jagannath8** [illacloud/illa-builder#2574]
Is your feature request related to a problem? Please describe.

-  Stats Generator will show all stats of Github

Describe the solution you'd like

- Add Github Stats Generator app

Describe alternatives you've considered

- N/A

Additional context

- Kindly assign it to me with appropriate Hacktoberfest labels

**Comment by harshhere905** [comment]
I would like to work on this issue ,Please assign me this issue.
