### ISSUE TITLE
[BUG] After receiving the Confirm Your Subscription email and clicking Get Start Button, redirected to 404Page

### ISSUE THREAD

**Issue by kiddjsh** [illacloud/illa-builder#2599]
### Description

After receiving the Confirm Your Subscription email and clicking Get Started redirected to 404Page

### Steps to reproduce

1. Go to 'Get Started' in README
2. Click on the link log in to 'ILLA Cloud'
3. Create account using option 'Sign in with GitHub'
4. Establish Authorization and Enter Dashboard
5. Wait for Confirm Your Subscription auto-generated system email
6. Once Confirmed Your Subscription email received, click button 'Get Start'
7. After clicking button brings you to 404Page https://www.illacloud.com/404

Note: The button get start does not conform to the proper flow of English language, should be "Get Started"

![getStartedREADME](https://github.com/illacloud/illa-builder/assets/70739345/0d9d84c0-5307-4d5f-9c8b-581b40068c4a)
![illaCloudLogin](https://github.com/illacloud/illa-builder/assets/70739345/a77d363b-5e35-4590-a61e-6b6210ba5293)
![emailConfirmSubscriptionILLA](https://github.com/illacloud/illa-builder/assets/70739345/5cf70b5e-4ad8-490f-b149-2e31be585012)
![404illaCloud](https://github.com/illacloud/illa-builder/assets/70739345/7561b300-0137-428b-9b83-8bcf5d6982ec)

### Version

cloud

### ILLA Builder Version

n/a

### Browser

Internet Explorer

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by donqu1xotechina** [comment]
Hey mate:
Noted! Thank you for your issue, I will check this out with our team and fix it ASAP. Meanwhile, welcome to join our Discord Community to stay in touch.

best,
ILLA Team.

**Comment by kiddjsh** [comment]
If you're able to add the hacktoberfest label to this issue, it would be appreciated. Thanks!

**Comment by AruSeito** [comment]
Hello,
Hacktoberfest does not count Issues, only PR, even if I label this issuse as Hacktoberfest

**Comment by kiddjsh** [comment]
Thanks!
I'd like to make a contribution towards the wording with the button within the email, updating the verbiage from "Get Start" to "Get Started". Can you direct me to where the file is housed?

**Comment by AruSeito** [comment]
@kiddjsh Hello,
Thank you for your willingness to contribute to this,These email template codes have not been backed up locally by us. So it can only be fixed by ourselves
