### ISSUE TITLE
After calling an endpoint, the builder constantly prompts me that there is no internet connection[BUG] 

### ISSUE THREAD

**Issue by NotTheRightGuy** [illacloud/illa-builder#2614]
### Description

After calling an endpoint, the page prompts that there is no internet connection, and constantly refreshing the page hence making it impossible to build something

### Steps to reproduce

1. Go to App Builder
2. Create an action to call an endpoint
3. After Success message you will receive a prompt that device is not connected to internet, even though I'm connected

The error goes away once the result from the endpoint gets removed and comes back once I call the endpoint again.

### Version

cloud

### ILLA Builder Version

3.1.1

### Browser

Google Chrome 117.0.5938.134

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

[Video showing error](https://streamable.com/hkrg5x)

**Comment by NotTheRightGuy** [comment]
The API endpoint I used is : http://api.quodb.com/search/{searchItem}?titles_per_page=1000&phrases_per_title=1000&page=1

**Comment by AruSeito** [comment]
@NotTheRightGuy 
Thanks for your feedback,i will check it soon

**Comment by AruSeito** [comment]
I'm very sorry for taking so long to reply to you. We have been unable to reproduce this issue.

We recently upgraded our network and it may solve your problem.

If you still have problems in the future, please open the issue again
