### ISSUE TITLE
[BUG] Partner section is not responsive as well as not centrally aligned 

### ISSUE THREAD

**Issue by ratishjain12** [illacloud/illa-builder#2632]
### Description

I want partner section to be centrally aligned as well as be mobile responsive 

I want to improve this section as you can see it is left aligned 
![image](https://github.com/illacloud/illa-builder/assets/43003421/0cbfac91-d7b7-4108-b7dd-bd2673f51ebd)

### Version

cloud

### ILLA Builder Version

-

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Ayush-Vish** [comment]
If this particular issue is not solved , @ratishjain12  Please assign it to me .

**Comment by AruSeito** [comment]
@Ayush-Vish @ratishjain12 
Hello,
What we need is left aligned. Although it may not be aesthetically pleasing right now
