### ISSUE TITLE
[Feature Requested] clarity of instruction/ guidelines with CONTRIBUTING.md

### ISSUE THREAD

**Issue by kiddjsh** [illacloud/illa-builder#2672]
I am opening a ticket on the CONTRIBUTING.md file. Thank you for the recent review on the punctuation changes I submitted. While reviewing the file for the contributing guidelines/ requirements I noticed some other issues with the documentation, and decided to leave these as a separate issue, or separate issues. The issues below are reflected in the JUL 26 commit d5f1300:

* At Line 30 there appears to be a broken link in the markdown script with "pnpm@8.x(https://pnpm.io/installation)" -- it would be nice to have Node.js LTS and pnpm hyperlinked with appropriate styling, within this verbiage. I was unclear what was meant here so did not make a change.

Other issues persist starting at Line 62:

* At Line 62 there is not a proper title or title structure here and there are no instructions or guidelines on what to do if the illa-builder-backend is not installed
* At Line 65 the statement structure could be reworded for clarity to "For Docker Developers" followed by instructions/ guidelines on how to get illa-builder/ illa-builder-backend up and running towards contributions
* At Line 67 the statement structure could be reworded for clarity to "Using Rust?" followed by the instructions/ guidelines on how to get illa-builder/  illa-builder-backend up and running towards contributions
* At Line 69 there are still punctuation, grammar, and run-on statements; there should be a space between "illa).illa" displaying as "illa). illa"; the "i" in illa should be capitalized after the period for consistency throughout the document; there should be a space between the comma and this at "9345`,this"; there are too many "And then" 
* At Line 80 there is not a proper title or title structure here, for clarity this could be reworded to "Not using Rust?", followed by complete proper instructions/ guidelines
* At Line 87 there is not a proper title or title structure here and there are no instructions or guidelines on what to do, for clarity it could be reworded as "For Go Developers" followed by complete proper instructions/ guidelines
* At Line 90 this appears to be the beginning of the instructions for Line 87, there are no proper guidelines, the letter "y" in "you" should be capitalized, the link is unclear could be meant for go developers

I understand the importance of your community, the project, and your guidelines directed to the community in Illa's CONTRIBUTING.md file; My intents are to help improve the quality of this documentation as needed, or if needed. If you would like to assign this request to me, I have an idea of what is intended in the document and would just need pointed to your install documentation--I'd be happy to help improve the guidelines, with approval. Thanks for your review.

**Comment by donqu1xotechina** [comment]
Hey @kiddjsh :

Apologies for the delay! You may work on this issue now. Thank you very much and looking forward to your work!

**Comment by kiddjsh** [comment]
I have reached out on discord for clarification on this documentation, please see my discord questions in General, also i need some clarification on Development Workflow section in the CONTRIBUTING.md file, i cannot seem to locate the directory, `apps/builder/.env.development.local`; I have checked several branches to include, main, beta, develop, etc and cannot seem to locate the file .env.development.local in the builder directory...
