### ISSUE TITLE
[Feature Requested] Adding Hover effect to Navbar elements

### ISSUE THREAD

**Issue by Kritika30032002** [illacloud/illa-builder#2684]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]
Adding Hover effect to Navbar elements so that user can know on which element user is clicking

**Describe the solution you'd like** A clear and concise description of what you
want to happen.
Adding Hover effect to Navbar elements

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by Kritika30032002** [comment]
Assign this to me!

**Comment by Kritika30032002** [comment]
Assign me this issue

**Comment by Devvrat1010** [comment]
Hi can you please assign this task to me
Thank You
