### ISSUE TITLE
[BUG] Mobile/tablet Navbar UI needs improvement

### ISSUE THREAD

**Issue by Kritika30032002** [illacloud/illa-builder#2685]
### Description

Navbar elements are not properly styled for mobile/tablet view.

### Steps to reproduce

open in mobile or tablet view

### Version

cloud

### ILLA Builder Version

1.0.0

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

UI needs improvement

![image](https://github.com/illacloud/illa-builder/assets/83400697/d01ad6ab-b261-42b2-b4a3-244632734387)

**Comment by Kritika30032002** [comment]
Assign this to me

**Comment by donqu1xotechina** [comment]
Hey @Kritika30032002 

Could you please reach out silencer.xyz at our discord community?  Because the engineer doesn't really get the issues you post.
We will need to communicate a little bit more.

**Comment by Kritika30032002** [comment]
okay
