### ISSUE TITLE
[AI Agent Idea] 

### ISSUE THREAD

**Issue by biswabaibhab007** [illacloud/illa-builder#2688]
This AI agent generates a random iconic quote from the famous Harry Potter series🎇

**Comment by biswabaibhab007** [comment]
@AruSeito assign this to me.

**Comment by OhmRamwala** [comment]
Please assign this to me if not assigned

**Comment by Devvrat1010** [comment]
Hi @biswabaibhab007 can you please assign this task to me .

**Comment by Devvrat1010** [comment]
@AruSeito Can you  please assign it to me

**Comment by biswabaibhab007** [comment]
@OhmRamwala and @Devvrat1010  I've already raised PR for the same
