### ISSUE TITLE
[AI agent idea] 

### ISSUE THREAD

**Issue by biswabaibhab007** [illacloud/illa-builder#2689]
This AI agent generates a random iconic quote from the famous sitcom F.R.I.E.N.D.S

**Comment by biswabaibhab007** [comment]
@AruSeito assign this to me

**Comment by biswabaibhab007** [comment]
@donqu1xotechina made the PR

**Comment by Devvrat1010** [comment]
Can you please assign this task to me

**Comment by biswabaibhab007** [comment]
@Devvrat1010 already made the PR
