### ISSUE TITLE
[BUG] UI n

### ISSUE THREAD

**Issue by thanmaisai** [illacloud/illa-builder#2690]
### Description

The UI has too much space between components, especially between the header and main content area, and between different sections of the main content area.
<img width="732" alt="Screenshot 2023-10-12 at 9 34 05 AM" src="https://github.com/illacloud/illa-builder/assets/91474486/a7322a14-669a-4fef-a15b-3fa0749553b7">

### Steps to reproduce

1. Go to ```https://www.illacloud.com/hacktoberfest2023#oss```
2. Set the screen size to 570X1336
3. Scroll down 

### Version

cloud

### ILLA Builder Version

1.0.0

### Browser

Firefox Version 118.0.1 (64-bit)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by thanmaisai** [comment]
**Assign me this issue ** @AruSeito !!

**Comment by AruSeito** [comment]
Hello, that's what we need. Not need to fix it
