### ISSUE TITLE
[ILLA App Idea]  Json to CSV Converter

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2699]
**Is your feature request related to a problem? Please describe.** 
Create a JSON to CSV Converter.

**Comment by AkshitMital** [comment]
#2769 Created a JSON to CSV Converter using ILLA AI

**Comment by seharbat00l** [comment]
I want to contribute. Can you assign this to me?

**Comment by AruSeito** [comment]
@seharbat00l Hello,someone has already made the PR

**Comment by giriprasathd** [comment]
@donqu1xotechina  can you assign me?

**Comment by shivanshu814** [comment]
@AruSeito can you please assign me this i have finished this i have to make pr only

**Comment by sharsha315** [comment]
Hi @donqu1xotechina, if the issue is not assigned and still open, can I have the opportunity to work on this issue.
