### ISSUE TITLE
[Illa App] Create a restaurant menu 

### ISSUE THREAD

**Issue by maitri-vv** [illacloud/illa-builder#2701]
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]
 I have made restaurant menu using illa app

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.
PR: #2846

**Comment by shirshakk** [comment]
please assign this issue to me for hactoberfest

**Comment by maitri-vv** [comment]
hey! i have already raised a PR for it. i waiting for it to get reviewed. PR: #2846
