### ISSUE TITLE
[BUG] Cannot clone repo

### ISSUE THREAD

**Issue by itzmidinesh** [illacloud/illa-builder#2771]
### Description

When I tried to clone the repo, I expected clone to succeed but got an error instead. I tried with Git Bash as well as the GitHub Desktop.

### Steps to reproduce

1. Fork the repo.
2. Clone the forked repo.
3. Cloning fails.
I tried cloning the repo without forking now, still getting the same error.

### Version

cloud

### ILLA Builder Version

3.1.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/illacloud/illa-builder/assets/5523347/0a9cec34-c635-4488-883e-e6ccccfa9ebb)
![image](https://github.com/illacloud/illa-builder/assets/5523347/b98db50d-7dae-41d9-aced-1453f2b51b64)
![image](https://github.com/illacloud/illa-builder/assets/5523347/ddc55ba2-d93c-4b49-8411-4fa54081efa5)

**Comment by AruSeito** [comment]
May be windows not support files in this naming format.I will modify the file name during working days

**Comment by itzmidinesh** [comment]
Thank you, appreciate the help.

**Comment by AruSeito** [comment]
@itzmidinesh Hello,you can try it again

**Comment by itzmidinesh** [comment]
> @itzmidinesh Hello,you can try it again

Yes, it's working now. Thank you.
