### ISSUE TITLE
[ILLA App idea] URL Decoder

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2853]
### Description

URL Decoder

### Additional Information

create an URL Decoder with ILLA Cloud.

**Comment by airwakz** [comment]
i can do this now

**Comment by airwakz** [comment]
@donqu1xotechina please assign this issue to me

**Comment by airwakz** [comment]
@donqu1xotechina  can uh elaborte tis topic

**Comment by airwakz** [comment]
![image](https://github.com/illacloud/illa-builder/assets/114548361/11a81b8a-d498-4d88-ac41-5f1f03884edd)
the components i need are not there so kindly give me an alternative
