### ISSUE TITLE
[ILLA App idea] QR Code Generator

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2858]
### Description

Generate QR codes in a variety of image (e.g. PNG, JPEG, SVG) formats and sizes. Export as an HTML <img> tag or a public URL with an App built by ILLA Cloud

### Additional Information

Generate QR codes in a variety of image (e.g. PNG, JPEG, SVG) formats and sizes. Export as an HTML <img> tag or a public URL with an App built by ILLA Cloud.

**Comment by ManishDait** [comment]
Hi, @donqu1xotechina I would Like to work on these.

**Comment by asif-reh** [comment]
Hi, @donqu1xotechina I would like to work on these.
