### ISSUE TITLE
[ILLA App idea] Create a CRUD App via ILLA Cloud and use PostgreSQL as data resources

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2897]
### Description

Create a CRUD App via ILLA Cloud and use PostgreSQL as data resources

### Additional Information

Create a CRUD App via ILLA Cloud and use PostgreSQL as data resources.

**Comment by Dhoni77** [comment]
Hi I would like to work on this can you assign this task to me
Thanks

**Comment by AudreyLin** [comment]
Hi @Dhoni77 .
Here is a helpful link to self assign this issue to you.
[Self Assign an Illa Issue](https://github.com/illacloud/illa-builder/issues/2820)
I hope this helps.  Happy Hacking.
