### ISSUE TITLE
[ILLA App idea] Use Hugging Face API to create a Pokemon Generator

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#2902]
### Description

use Hugging Face API to create a Pokemon Generator

### Additional Information

use Hugging Face API to create a Pokemon Generator

**Comment by vishalkhoje** [comment]
Hi @donqu1xotechina 
Can you please assign this ticket to me? 
/assign @vishalkhoje

**Comment by vishalkhoje** [comment]
Hi @akshayw1 ,

I kindly request that you consider allowing other members the opportunity to take on assigned issues. I've observed that you have self-assigned three tickets, some of which are older and still pending completion. I appreciate your understanding and willingness to provide others with the chance to contribute.

**Comment by airwakz** [comment]
@vishalkhoje  can uh assign this task to me

**Comment by akshayw1** [comment]
@vishalkhoje Sure Vishal, I can consider and understand your request, you could proceed assigning issue, Your self by using bot prompt.  Happy contributing!!!

**Comment by vishalkhoje** [comment]
I am working on it, I will raise PR very soon.

**Comment by vishalkhoje** [comment]
Hello @donqu1xotechina 
can you please review my PR
