### ISSUE TITLE
[AI Agent idea] ADVANCED RECIPE TELLER WITH OTHER DETAILS!

### ISSUE THREAD

**Issue by itztani** [illacloud/illa-builder#3084]
### Description

Amazing recipe teller. Providing other details like dish history , benefits etc...  also you can include and exclude recipe items then AI makes u a recipe according to it .  otherwise, you can add your country name and AI try to take recipe items which is available in your country..

### Additional Information

Its very helpful...GO A HEAD AND TRY IT!!!

**Comment by itztani** [comment]
:/assign @<itztani>

**Comment by AruSeito** [comment]
Because there has been no progress for too long, it will be closed
