### ISSUE TITLE
[AI Agent idea] Word Antonym Finder

### ISSUE THREAD

**Issue by Rutam21** [illacloud/illa-builder#3091]
### Description

This AI Agent find the antonym of the given word.

### Additional Information

Build an AI Agent for the above use case using Illa Cloud.

**Comment by manmohanhunjan** [comment]
hey @Rutam21 how do you link the issue?

**Comment by Rutam21** [comment]
Hello @manmohanhunjan, Mention something like `Fixes #TicketNumber`. This way it connects to the ticket.

**Comment by manmohanhunjan** [comment]
Thank you it worked for me.
