### ISSUE TITLE
[AI Agent idea] Square Root Finder

### ISSUE THREAD

**Issue by Rutam21** [illacloud/illa-builder#3094]
### Description

This AI Agent find the square root of a given number.

### Additional Information

Build an AI Agent for the above use case using Illa Cloud.

**Comment by mdsahilnoob** [comment]
I want to work on this issue, could you assign this issue to me? @Rutam21

**Comment by Rutam21** [comment]
@mdsahilnoob Hello there, This issue has been worked upon already. Feel free to find other issues that are unassigned ir create some new ones with your own AI Agent ideas. Thanks.

**Comment by mdsahilnoob** [comment]
Thanks for letting me know!! @Rutam21
