### ISSUE TITLE
[AI Agent idea] Chat with an AI Pet Agent

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [illacloud/illa-builder#3127]
### Description

Chat with an AI Pet Agent

**Comment by Emmarie-Ahtunan** [comment]
I worked on this.

**Comment by Emmarie-Ahtunan** [comment]
assigned to @Emmarie-Ahtunan

**Comment by AruSeito** [comment]
Because there has been no progress for too long, it will be closed
