### ISSUE TITLE
Some Minor Design issues with https://www.illacloud.com 

### ISSUE THREAD

**Issue by myselfprincee** [illacloud/illa-builder#3139]
Hello, I was on the illacloud website and noticed some Hover animation issues on the website. Please see the Video to understand my issue better.

https://github.com/illacloud/illa-builder/assets/114233864/d35e6692-8c9f-4f26-8285-19b54eb89da8

You can see that we have some button hover animation inconsistencies on the website.

**1 answer could be that The Hover animation has been only applied to main buttons But, Please let me know I would love to fix :) @AruSeito**

**Comment by AruSeito** [comment]
Thank you for your feedback. I fully agree with your opinion. But we need to wait for confirmation from our designer

**Comment by AruSeito** [comment]
Yeah, wait for their confirmation and they will comment and contact you

**Comment by myselfprincee** [comment]
Okay. Thanks :)

**Comment by myselfprincee** [comment]
> Yeah, wait for their confirmation and they will comment and contact you

Any Updates ??

**Comment by AruSeito** [comment]
Thank you very much for your feedback. The feedback received after confirming with the designer is that the design is like this.

**Comment by myselfprincee** [comment]
You're Welcome :) Happy to contribute even that much.
