### ISSUE TITLE
[BUG] Docker all-in-one Image > Scripts > 404 - page not found error

### ISSUE THREAD

**Issue by kiddjsh** [illacloud/illa-builder#3165]
### Description

When clicking on the scripts link you're redirected to a 404 - page not found error

### Steps to reproduce

1. Go to 'https://www.illacloud.com/docs/docker-all-in-one-image'
2. Under the section `Description`, click on the link 'scripts'
3. When clicking on the link `scripts`, your redirected to a 404 Error Page - page not found

### Version

cloud

### ILLA Builder Version

n/a

### Browser

Internet Explorer

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

The install instructions for deploying docker state the following: "Build illa utils an all-in-one image and run it on your machine. You can check out the scripts file in the [scripts](https://github.com/illacloud/deploy-illa-manually/blob/main/docker/scripts) folder for more details." However, there are no scripts to review.

**Comment by karminski** [comment]
Thanks for issue this! We already fixed it.
