### ISSUE TITLE
[BUG] ILLA CLI Usage: illa <COMMAND>; i.e. `illa doctor` command generates error "command not found"

### ISSUE THREAD

**Issue by kiddjsh** [illacloud/illa-builder#3175]
### Description

When executing the command `illa doctor` at ILLA CLI, "command not found" error received

### Steps to reproduce

1. Go to 'https://www.illacloud.com/docs/illa-cli'
2. Download the `illa-x86_64-linux.tar.gz` file  
3. Follow instructions at 'After downloading the CLI, you will have to make it executable. Let’s take the illa-linux for example:

#### download illa cli binary file
> `wget https://github.com/illacloud/illa/releases/latest/download/illa-x86_64-linux.tar.gz`

#### unpack the file
> `tar -zxvf illa-x86_64-linux.tar.gz`

> `cd illa-x86_64-linux`

> `chmod +x illa`

#### run the illa cli
> `./illa` '

4. After running `./illa` to launch the illa cli, HELP indicates the usage command as: `illa <COMMAND>`, when running the command as, for example, `illa doctor` an error is received "command not found"
5. When utilizing the command as `./illa doctor` a response is then received back stating checking for self-host prerequisites, and a response on no running docker image found

### Version

cloud

### ILLA Builder Version

n/a

### Browser

Internet Explorer

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Please see my Ubuntu snippet, running on Windows (note: my docker engine is currently running):

![illaCommands](https://github.com/illacloud/illa-builder/assets/70739345/4300025b-6b60-48a8-9b24-87c6333cb218)

**Comment by karminski** [comment]
@kiddjsh This is actually the program does not detect that Docker is running. We've added new tips for this.
![image](https://github.com/illacloud/illa-builder/assets/1567626/83ad652f-163c-440a-bdd5-04789d6dfcd7)

**Comment by kiddjsh** [comment]
@AruSeito @karminski 

The ticket that I opened is not in reference to the message "Please check the status of docker."

As you can see from my terminal directory: illa-x86_64-linux# `illa doctor` is the input command
The following output response shows `illa: command not found`
It's not until command `./illa doctor` is used that is executes a running installation check
The guide does not specify that the command needs to be run from any directory other than `illa-x86_64-linux`

Though in the build out being used by @karminski command `illa deploy --self` is functioning properly 
So, there is some kind of step missing, or something different between the build setups from one environment to the next.
