### ISSUE TITLE
[BUG] Upgrade label on wrong option

### ISSUE THREAD

**Issue by manancodes** [illacloud/illa-builder#3187]
### Description

When trying to make an App private, the Upgrade tooltip is rendered on the wrong option (public)

### Steps to reproduce

1. Go to https://cloud.illacloud.com/
2. Login with your account
3. Go to your apps
4. Click on the dropdown to make the app private/public.
5. The `Upgrade` label is rendered on the wrong option. 

### Version

cloud

### ILLA Builder Version

3.2.1

### Browser

Edge Browser Version 117.0.2045.31 (Official build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It should be rendered on the `Private` option because that is the paid feature. And please assign this to me, would love to work on it.
<img width="480" alt="Screenshot 2023-10-23 at 3 58 50 PM" src="https://github.com/illacloud/illa-builder/assets/54790263/e4eb1c6d-5b34-4ed4-9b50-5b8446bc71c3">

**Comment by AruSeito** [comment]
The expectation is like this. It's not a bug.

**Comment by manancodes** [comment]
Public is not a paid feature. So why put the label there? 

To use the Private feature, we need an upgrade. Shouldn't the label be there?
