### ISSUE TITLE
[ILLA App idea] Voice Generator with Hugging Face

### ISSUE THREAD

**Issue by donqu1xotechina** [illacloud/illa-builder#3247]
### Description

Using Hugging Face API to create a Voice Generator 

### Additional Information

Please use this Model from Hugging Face:
https://huggingface.co/spaces/Xenova/text-to-speech-client, to generate a Voice Generator.

**Comment by sharsha315** [comment]
Hi @donqu1xotechina, can I have the opportunity to work on this issue.
