### ISSUE TITLE
[Feature Requested] : Adding Contribution section in the REadme.md file. 

### ISSUE THREAD

**Issue by Kalyanimhala** [illacloud/illa-builder#3315]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.

![contributors](https://github.com/illacloud/illa-builder/assets/147402107/40f07ed5-bdb5-4188-837c-100c49315d56)

**Comment by Kalyanimhala** [comment]
@Alkaison kindly assign me this #3315 issue, I want to work on it. Thank You!!

**Comment by Alkaison** [comment]
Hi @Kalyanimhala, I'm not the maintainer of this project, so I can't assign the issue it to you. You can use the command `/assign @Kalyanimhala` to get this assigned to yourself.

**Comment by Kalyanimhala** [comment]
okay Thank You!

**Comment by AruSeito** [comment]
Because there has been no progress for too long, the issue will be closed
