### ISSUE TITLE
[BUG] The "click here" link , in Self-Hosted section of the documentation leads to 404 page

### ISSUE THREAD

**Issue by siddarth2810** [illacloud/illa-builder#3354]
### Description

When I clicked on the "click here" link present in the self-hosted section it led to a 404 error page. 

### Steps to reproduce

1. Go to 'https://github.com/illacloud/illa-builder'
2. Scroll down to 'self-hosted' section 
3. click on the 'click here' link
4. This is leading to 404 Page

### Version

cloud

### ILLA Builder Version

1.0.0

### Browser

In Google Chrome Version 118.0.5993.88 and in Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

![Screenshot from 2023-10-31 09-05-26](https://github.com/illacloud/illa-builder/assets/110726331/a5b98144-f8e1-4f9f-8fdd-6e6fdf387ec1)

This is the result after clicking the link
 
![Screenshot from 2023-10-31 09-20-22](https://github.com/illacloud/illa-builder/assets/110726331/b15fc591-8e86-4b3a-b735-3c37ebefe153)

I believe the redirecting link is broken.

**Comment by shubhusion** [comment]
Kindly assign this issue to me. I will make the PR asap.
