### ISSUE TITLE
[BUG] Passing datarange startvalue and endvalue as arguments failed

### ISSUE THREAD

**Issue by xiaobai721** [illacloud/illa-builder#3397]
### Description

Passing datarange startvalue and endvalue as arguments into a oracle sql runs failed

### Steps to reproduce

data range component:
![1699405115370](https://github.com/illacloud/illa-builder/assets/19648428/0953cce7-a6c9-47a7-b413-ca7aa8a8c061)

sql as below:
![1699405154923](https://github.com/illacloud/illa-builder/assets/19648428/762c0c94-c9ac-491f-8eeb-856f26f0187e)

error message:
![1699405191850](https://github.com/illacloud/illa-builder/assets/19648428/7f83e04e-dba0-431e-a674-14f6da90824b)

docker logs:
![1699405227658](https://github.com/illacloud/illa-builder/assets/19648428/97275f41-d4a7-47da-99ed-9fdd864b624c)

### Version

self-host

### ILLA Builder Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by karminski** [comment]
@xiaobai721 把{{dataRange1.StartValue}} 外面的单引号去掉试试? safe 模式会自动escape, 因此不需要外面包裹引号. 如果想要用引号可以切换到unsafe模式.

**Comment by xiaobai721** [comment]
> @xiaobai721 把{{dataRange1.StartValue}} 外面的单引号去掉试试? safe 模式会自动escape, 因此不需要外面包裹引号. 如果想要用引号可以切换到unsafe模式.

好像去掉了也不行。。。还是报run action error: ORA-00911: invalid character
![image](https://github.com/illacloud/illa-builder/assets/19648428/66905c8f-5016-4e2f-a55d-a615f5be5f41)
![1699490726518](https://github.com/illacloud/illa-builder/assets/19648428/3a429b15-6799-4183-952e-e77e62dcc9b0)

**Comment by karminski** [comment]
@xiaobai721 我们针对这个问题做了个补丁，本周就会发布。发布后我会恢复这个issue。

**Comment by karminski** [comment]
@xiaobai721 hi, 该问题已修复，在safe模式下，请使用：
```sql
where REQ_DATE >= TO_DATE({{dateRange1.startValue}}, 'yyyy-mm-dd')
```

unsafe 模式下请使用:
```sql
where REQ_DATE >= TO_DATE('{{dateRange1.startValue}}', 'yyyy-mm-dd')
```

即可完成查询.

由于dateRange组件传入的值是字符串, 因此必须使用函数TO_DATE进行转换后查询.

**Comment by xiaobai721** [comment]
@karminski 抱歉我之前没说清楚，REQ_DATE也是字符串格式的，YYYYMMDD形式。DateRange组件的format也设置为了YYYYMMDD，所以我本以为直接用REQ_DATE >= ‘{{dataRange1.StartValue}}'就可以，结果报出上面的错误。
btw，您这个补丁是修复在哪里了呢？我直接docker pull illasoft/illa-builder latest 可以吗？

**Comment by karminski** [comment]
@xiaobai721 可以的，直接拉取就可以。应该问题都修复了，可以重新拉取docker镜像试一下。

**Comment by xiaobai721** [comment]
> @xiaobai721 可以的，直接拉取就可以。应该问题都修复了，可以重新拉取docker镜像试一下。

测试成功，感谢呀~~

**Comment by karminski** [comment]
@xiaobai721 感谢反馈👍
