### ISSUE TITLE
[BUG] Input widgets don't clean javascript expressions

### ISSUE THREAD

**Issue by sandstone991** [illacloud/illa-builder#3442]
### Description

When inserting javascript experssions into an input widget, I expected it to be treated as text, not to actually get evaluated

### Steps to reproduce

See video below

https://github.com/illacloud/illa-builder/assets/61756360/5e3aba89-c04c-40ad-8d60-64fc9e6d936c

### Version

cloud

### ILLA Builder Version

Latest

### Browser

Chrome 119

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
Thank you for your feedback. We will fix it as soon as possible

**Comment by Ghanem10** [comment]
Hi, I'm attempting to contribute to fix this but when running it in development mode, I'm facing some errors related to the i18n JSON files that seem to be missing. These files are being ignored as per the .gitignore file. I wonder how to run the app locally.

**Comment by AruSeito** [comment]
fixed
