### ISSUE TITLE
docker部署网页无连接

### ISSUE THREAD

**Issue by yyf127** [illacloud/illa-builder#3490]
### Description

docker部署网页无连接

### Steps to reproduce

运行环境rk3566+armbian，docker版本24.0.7，镜像版本local，部署命令
docker run -d \
    --name illa-builder \
    -v /opt/illa/database:/opt/illa/database \
    -v /opt/illa/drive:/opt/illa/drive \
    -p 2022:2022 \
    illasoft/illa-builder:local
![QQ图片20231203233035](https://github.com/illacloud/illa-builder/assets/66797877/f64f9210-6e8d-463c-a08c-8e799ef65a62)

### Version

self-host

### ILLA Builder Version

local

### Browser

edge

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

日志
[illa-builder-20231203234444.log](https://github.com/illacloud/illa-builder/files/13539493/illa-builder-20231203234444.log)

**Comment by karminski** [comment]
@yyf127 hi, 目前self-host镜像仅支持x86-64架构CPU哈, arm64的支持还在适配中.

**Comment by karminski** [comment]
@yyf127 另外envoy组件提示内存不够用了, 可以尝试释放一些内存后再启动试试.

envoy 的报错信息(在你提供的日志中):

```
 FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 
 ```

**Comment by yyf127** [comment]
> 另外envoy组件提示内存不够用了， 可以尝试释放一些内存后再启动试试.
> 
> envoy 的报错信息（在你提供的日志中）：
> 
> ```
>  FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size) 
> ```

哦，那好的，等以后适配好arm我再试试

**Comment by AruSeito** [comment]
@yyf127 您好，目前 latest 镜像已经适配 arm，您可以升级再次尝试。

**Comment by AruSeito** [comment]
您好，因为太长时间没有收到您的反馈，因此将该 Issue 关闭。
如果本次更新并没有解决您的问题，您可以重新打开该 Issue。
