### ISSUE TITLE
[BUG] Redis connection string is not parsed properly if a password contains "@"

### ISSUE THREAD

**Issue by PlkMarudny** [illacloud/illa-builder#3565]
### Description

Cannot connect to Redis if password contains "@"; the url string is not parsed properly

### Steps to reproduce

1. Try to use a password that contains '@' in the Redis connection string; it is not parsed properly

### Version

self-host

### ILLA Builder Version

24.0.5

### Browser

Google Chrome 110

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by MuaazOsaidTahir** [comment]
As "@" is a special character, I guess it should be encoded before passing in using the built-in JS method **encodeURIComponent**

**Comment by AruSeito** [comment]
Thank you for your feedback. We will verify as soon as possible

**Comment by AruSeito** [comment]
Hello, the issue has been fixed.

If you are in the cloud version, please refresh the page.

If you are a self host version, please update the image.

If you encounter this issue again in the future, please reopen the issue.
