### ISSUE TITLE
本地部署后没有用户注册页面（最新版本）

### ISSUE THREAD

**Issue by duanshuaimin** [illacloud/illa-builder#3627]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
本地容器部署后只有登录页面，没有注册页面，正常的吗？记得最初的版本有注册页面。
illa版本1.2.14

**Comment by duanshuaimin** [comment]
<img width="1792" alt="截屏2024-01-06 11 36 24" src="https://github.com/illacloud/illa-builder/assets/535940/12e566e9-da03-4da4-b0e2-cf8de5f5b099">

**Comment by smallSohoSolo** [comment]
Sorry, the open source version only support one person to use.

**Comment by duanshuaimin** [comment]
缺省用户文档没看到

**Comment by duanshuaimin** [comment]
看到了
