### ISSUE TITLE
[BUG] "MUI X Missing license key" watermark on DataGrid element

### ISSUE THREAD

**Issue by IvanDrag0** [illacloud/illa-builder#3640]
### Description

When I add a new DataGrid, it contains a watermark with the text "MUI X Missing license key".

![image](https://github.com/illacloud/illa-builder/assets/24702285/f73e65b8-894a-4c42-87ab-796670f4f948)

### Steps to reproduce

1. Create a new application
2. Add a new DataGrid element

### Version

self-host

### ILLA Builder Version

4.3.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Using the illasoft/illa-builder:latest image (4.3.1).

**Comment by AruSeito** [comment]
License key needs to be prepared by yourself when you use self-host

**Comment by dumy** [comment]
Where add my key ?

**Comment by AruSeito** [comment]
@dumy 
Hello, we currently do not support customizing this key. We are expected to release a new version next week so that the self-host version can also be customized.

**Comment by AruSeito** [comment]
@dumy 
At next version:
You can add 'ILLA_MUI_LICENSE' to environment variable.
like:`ILLA_MUI_LICENSE=xxxxxxxx pnpm build:self`
