### ISSUE TITLE
不明白怎么处理复杂的业务逻辑，事务管理？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [illacloud/illa-builder#3733]
不明白怎么处理复杂的业务逻辑，事务管理？没有人有跨标表，多表更新的需求吗？

**Comment by AruSeito** [comment]
您好，您能举一些简单的例子或者类比一下使用场景吗？

**Comment by liuhuapiaoyuan** [comment]
就是我看了文档没有找到数据库更新的事务管理？难道只能单表 crud 吗？比如一个仓管 wms，会涉及两个表的关联更新，也需要一些逻辑运算，这如何实现呢？

**Comment by AruSeito** [comment]
这种您只能通过在 sql 内写事务，或者 自己封装幂等接口。

**Comment by liuhuapiaoyuan** [comment]
是否有暴露直接 sql 的 api 操作呢？

**Comment by AruSeito** [comment]
![image](https://github.com/illacloud/illa-builder/assets/41471697/0820cc3c-cbbb-4fa0-949f-b5a14c226ceb)
您好，您可以加入我们的微信用户交流群。咱们可以详细聊一下使用场景。

**Comment by liuhuapiaoyuan** [comment]
嗯。但是我觉得一个业务系统应该要具备逻辑编排的能力，要不只能是一个表单录入功能，实际意义不大

**Comment by karminski** [comment]
@liuhuapiaoyuan hi，我们有flow系统，可以进行逻辑编排，可以体验一下：

![image](https://github.com/illacloud/illa-builder/assets/1567626/8278da5a-cc33-4b79-a2f1-d499d3be1c1f)

**Comment by karminski** [comment]
closed due to no response.
