### ISSUE TITLE
[BUG] Map component not working; Google Maps throwing an InvalidKeyMapError

### ISSUE THREAD

**Issue by junkaitan** [illacloud/illa-builder#3802]
### Description

When I add a Map component to the app, the Map component shows an "Oops! Something went wrong" message instead of displaying the map. Checking the JavaScript console reveals that there is a Google Maps JavaScript API error: InvalidKeyMapError

### Steps to reproduce

1. Add a Map component to your app
2. You will get a "Oops! Something went wrong" message within the Map component.
3. See Google Maps error in browser/JavaScript console.

### Version

cloud

### ILLA Builder Version

4.8.3

### Browser

Google Chrome Version 126.0.6478.128 (Official Build) (64-bit)

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/user-attachments/assets/a2da20bc-549a-4ea6-b25f-54bd807fc346)

**Comment by AruSeito** [comment]
Hello,we fixed this.
