### ISSUE TITLE
Signup screen does not recognize email addresses that contain a +

### ISSUE THREAD

**Issue by christophberger** [illacloud/illa-builder#534]
### Description

When I sign up, I expect to be able to use an email address with a plus sign in it, like mail+illa@mydomain.com. Instead, the signup form says, "invalid email address"

### Steps to reproduce

1. Go to the signup screen
2. Fill out all fields
   - In the email address field, enter an email address that contains a plus sign, e.g. mail+illa@mydomain.com
4. Click the Create Account button
5. See error message: "Please enter a valid email address"

### ILLA Builder Version

fast-try.illacloud.com

### Browser

Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
Thanks for your feedback！we will fix it soon

**Comment by AruSeito** [comment]
Hello,we fixed it.You can try it again

**Comment by christophberger** [comment]
Thanks for the fix, it works! I was able to sign up. This issue can be closed.
