### ISSUE TITLE
不兼容旧版  chrome 内核浏览器，不兼容 firefox developer 浏览器，表现为无法拖拽

### ISSUE THREAD

**Issue by geekyouth** [illacloud/illa-builder#595]
### Description

无法拖拽组件到画布

### Steps to reproduce

1、https://www.illacloud.com/zh-CN/docs/illa-cli#illa-cli 根据这里的文档安装 illa；
2、启动之后，使用版本号为 chrome (Chromium 86.0.4240.198) 浏览器打开 WEBUI；
3、新建一个项目，开始编辑，拖拽组件到画布，鼠标显示禁止图标；
![image](https://user-images.githubusercontent.com/12899262/204683455-d736aca3-ac7a-4cc7-ba2e-ca9a64efcc66.png)

4、我怀疑chrome 浏览器本身有问题，于是打开火狐开发者版本浏览器87.0b9 (64 位)，依然无法拖拽组件到画布；
5、于是我升级了原生 chrome 浏览器到108.0.5359.72（正式版本） （64 位），果然可以拖拽了；
![image](https://user-images.githubusercontent.com/12899262/204683937-b8da7847-9687-4928-a556-70992cd477c8.png)

### ILLA Builder Version

1.2.5

### Browser

chrome (Chromium 86.0.4240.198)

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows

**Comment by AruSeito** [comment]
您好，我们后续会进行一个兼容问题的处理。
