### ISSUE TITLE
[BUG] `--server-addr`不生效

### ISSUE THREAD

**Issue by myuanz** [illacloud/illa-builder#597]
### Description

使用 `illa deploy` 时  `--server-addr` 不生效

### Steps to reproduce

1. 运行`illa deploy --port=10000 --server-addr=10.20.34.150 --self`
2. 得到输出`✨  ILLA Builder started, please visit http://localhost:10000    `
3. 无法通过`10.20.34.150:10000`访问

### ILLA Builder Version

1.2.5

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by naj1n** [comment]
@myuanz I run the same command with a public IP address, and it works. So, it's difficult for me to predict what will happen with a private IP address.

**Comment by myuanz** [comment]
Hello, `10.20.34.150` is a class B address, and the server and my device are in the same LAN (I connect to it through ssh). So I think whether it's a public IP or not might not be relevant to the problem.
```
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b0:7b:25:20:05:55 brd ff:ff:ff:ff:ff:ff
    inet 10.20.34.150/20 brd 10.20.47.255 scope global dynamic noprefixroute enp2s0
       valid_lft 17281sec preferred_lft 17281sec
    inet6 2400:dd02:1011:2:12d2:96bb:bc75:18e6/128 scope global dynamic noprefixroute 
       valid_lft 558sec preferred_lft 558sec
    inet6 fd00:6cb1:5823:576c:b487:705:704c:65bb/64 scope global deprecated dynamic noprefixroute 
       valid_lft 30291sec preferred_lft 0sec
    inet6 fe80::a4fe:1522:aeb3:73a7/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by naj1n** [comment]
@myuanz please provide more information on this problem, such as docker logs, API requests, and responses.

**Comment by karminski** [comment]
closed due to no response over 5 days.
