### ISSUE TITLE
无法注册用户

### ISSUE THREAD

**Issue by CaiJingLong** [illacloud/illa-builder#632]
### Description

使用 docker 部署的 illa-builder 镜像

### Steps to reproduce

填入注册信息后提交时报错

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/14145407/205872213-da6c5a43-a6a4-4667-bcbf-fdc82809b1ef.png">

查看网页控制台：

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/14145407/205872387-011fefbf-e866-4e59-bc80-84a54f99b7a3.png">

报错接口的返回信息
```json
{
    "errorCode": 400,
    "errorMessage": "validate verification code error: token contains an invalid number of segments"
}
```

### ILLA Builder Version

docker-latest v1.4.2

### Browser

Edge 107.0.1418.62

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

不能注册新用户
数据库初始化成功后查看到有一个root用户，默认密码可用

**Comment by AruSeito** [comment]
您好，请问您请求的后端地址是什么？方便提供个可复现链接吗？

**Comment by karminski** [comment]
@CaiJingLong hi，我们刚刚更新了illa 1.5, 请使用 [illacli](https://github.com/illacloud/illa) 部署. 
另外本地部署现在取消了验证码登录, 可以使用默认的用户名 **root** 密码 **password** 登录.

**Comment by longix** [comment]
> @CaiJingLong hi，我们刚刚更新了illa 1.5, 请使用 [illacli](https://github.com/illacloud/illa) 部署. 另外本地部署现在取消了验证码登录, 可以使用默认的用户名 **root** 密码 **password** 登录.

是要用cargo install illa下载吗
我通过链接下载windows的illa，或者update，都还是1.2.6

**Comment by smallSohoSolo** [comment]
我们无法删除你本地的docker image，需要手动删除之后重新install

**Comment by qdriven** [comment]
删除了也没法使用

**Comment by karminski** [comment]
@longix 1.2.6 是部署工具 illacli 的版本, 这里的版本指的是 illa套件本身的版本. illacli 部署工具可以使用cargo安装, 也可以直接在这里下载: https://github.com/illacloud/illa/releases

**Comment by karminski** [comment]
@qdriven 请提供更多故障信息或者单独开一个 issue.

**Comment by karminski** [comment]
Issue closed due to no feedback over 5 days.
