### ISSUE TITLE
多页面问题

### ISSUE THREAD

**Issue by TBusan** [illacloud/illa-builder#674]
### Description

当有多个页面的时候，操作其他页面，比如拖拽组件到画布中，总是会跳转到第一个页面。

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Builder Version

1.0.0

### Browser

chrome 108.0.5359.72

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by smallSohoSolo** [comment]
@AruSeito 关注下

**Comment by AruSeito** [comment]
您好，因为没收到您的后续反馈且该 issue 距离上次活跃时间已经超过一周，现在将做关闭处理。如果您后续还遇到该问题，欢迎再次打开该 issue。
