### ISSUE TITLE
表格手动排序后，显示的页码与页面内容不符

### ISSUE THREAD

**Issue by chudaokai** [illacloud/illa-builder#675]
### Description

表格手动排序后，显示的页码与页面内容不符

### Steps to reproduce

1. 添加一个表格，查询数据库内容，并保证多于1页内容
2. 切换到第二页，然后点击某一列进行排序
3. 页面内容会变为排序后第一页内容，但页码仍然显示第二页

### ILLA Builder Version

1.2.6

### Browser

Google Chrome 93

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

illa通过cargo部署在centos服务器

**Comment by echoxyc** [comment]
This is bug. We'll fixed it in the near future.

**Comment by laohuzhigege** [comment]
thankyou

**Comment by echoxyc** [comment]
您好，目前该问题已修复，您可以再次尝试。如果再次遇到问题，欢迎您创建新的 Issue进行反馈。
