### ISSUE TITLE
修改Redis数据库索引后，无法保存资源

### ISSUE THREAD

**Issue by ljh19930603** [illacloud/illa-builder#676]
### Description

修改Redis数据库索引后，无法保存资源

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Builder Version

1.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/25343841/207295094-1cb308f7-8f3f-4d82-8d2c-bbbc98e88855.png)

**Comment by shandamengcheng** [comment]
你好，我们会尽快修复此问题
