### ISSUE TITLE
修改Action-事件处理器-请求成功事件并保存，页面会卡住

### ISSUE THREAD

**Issue by 51a25e71-cb5e-4c1b-b0e7-fe24f6f2e555** [illacloud/illa-builder#687]
### Description

尝试在执行Action后，展示修改成功的回调内容，遇到该问题（可能下述操作是不合法的）

### Steps to reproduce

1. 创建项目test，并编辑
2. 创建一个redis1的Action
3. 创建该Action的请求成功事件
5. 修改该事件：动作为展示通知，描述为{{redis1.content.successEvent}}，并保存
6. 此时页面会卡住

ps：关闭页面并重新打开，所有组件都会消失，将之前修改的事件描述清空再保存，所有组件就会重新出现

### ILLA Builder Version

1.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
您好，这是一个 BUG，目前在依赖成环部分处理有些问题。当您在成功事件中读取自身的成功事件其实是一个环状调用数据结构，这种操作应该是不被允许的。

**Comment by laohuzhigege** [comment]
good thankyou

**Comment by AruSeito** [comment]
您好，目前该问题已修复，您可以再次尝试。如果再次遇到问题，欢迎您创建新的 Issue进行反馈。
