### ISSUE TITLE
部署后，无法登录

### ISSUE THREAD

**Issue by deagon** [illacloud/illa-builder#688]
### Description

部署后无法登录

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3887050/208869098-6f76fd03-bda2-4858-aabc-be77539ef8bc.png)

使用 `docker-compose` 部署

### ILLA Builder Version

1.0.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

默认账号有修改吗？

**Comment by karminski** [comment]
@deagon 你好, 
- 目前只有 all-in-one 镜像 (即 self-host版本) 支持默认用户名和密码登录. 
- docker compose (和 k8s) 部署的是 slim 镜像 (cloud 版本). 
- cloud 版本是提供生产环境部署的, 为了安全考虑目前不支持默认用户名和密码登录.

**Comment by deagon** [comment]
![image](https://user-images.githubusercontent.com/3887050/208886904-bf72d6c1-e165-4296-b1f1-beefbcc5a8e7.png)

使用 self-host 版本，仍然报错？
