### ISSUE TITLE
this Cargo does not support nightly features, but if you   switch to nightly channel you can add

### ISSUE THREAD

**Issue by reggi** [illacloud/illa-builder#701]
### Description

this Cargo does not support nightly features, but if you   switch to nightly channel you can add

### Steps to reproduce

➜  ~ cargo install illa
    Updating crates.io index
  Downloaded illa v1.2.6
error: failed to parse manifest at `/Users/thomasreggi/.cargo/registry/src/github.com-1ecc6299db9ec823/illa-1.2.6/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature

### ILLA Builder Version

v1.2.6

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by karminski** [comment]
@reggi Hi, the "illa" is a deploy CLI tool, it will always pull the latest version of illa-builder (our low code tools) docker image.  
To fetch the latest version of illa-builder, please run with:

```bash
illa upgrade
```

And we just tested that:
```
cargo 1.66.0 (d65d197ad 2022-11-15)
cargo 1.68.0-nightly (c994a4a63 2022-12-18)
```
are installed illa successfully. 

And the "Edition 2021"  is part of the stable channel now (https://forge.rust-lang.org/index.html).
Please check your cargo version and update it. try:

```
rustup default nightly && rustup update
```

or
```
rustup default stable && rustup update
```

**Comment by AruSeito** [comment]
Because it has not had recent activity. It will be closed if no further activity occurs.
