### ISSUE TITLE
单击按钮，成功执行redis命令后，文本输入框内的值会被清空

### ISSUE THREAD

**Issue by 51a25e71-cb5e-4c1b-b0e7-fe24f6f2e555** [illacloud/illa-builder#714]
### Description

尝试使用多个文本输入框填入各种参数，单击按钮提交参数到数据库，遇到该问题

### Steps to reproduce

1. 创建项目: test
2. 创建Action: redis1，命令为“HMSET test {{input1.value}} {{input2.value}} {{input3.value}} {{input4.value}}”，并保存
3. 创建4个文本输入框和1个按钮
4. 给按钮绑定单击事件，动作为：触发请求，Query为redis1，并发布
5. 在4个文本输入框内输入1、2、3、4，并单击按钮
6. 查看结果：所有文本输入框内的内容都被清空了

期望：不清空内容。会方便修改某项参数后再次提交。

### ILLA Builder Version

1.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by karminski** [comment]
@ljh19930603 你好, 表单配置项中有"提交成功后重置输入内容"的选项, 默认是打开的, 关闭该选项就不会清空文本输入框的内容了.

![image](https://user-images.githubusercontent.com/1567626/209298013-4151b874-ccfe-4e0a-a9b2-985ccf2bb2c5.png)

**Comment by ljh19930603** [comment]
> @ljh19930603 你好, 表单配置项中有"提交成功后重置输入内容"的选项, 默认是打开的, 关闭该选项就不会清空文本输入框的内容了.
> 
> ![image](https://user-images.githubusercontent.com/1567626/209298013-4151b874-ccfe-4e0a-a9b2-985ccf2bb2c5.png)

你好，我之前的操作是没有使用表单的，现在我尝试先创建表单，在表单的区域内再新建文本输入框，其他操作不变。此时我遇到了另一个问题，无法在这些输入框内输入任何内容。（组件布局如下图）

![image](https://user-images.githubusercontent.com/25343841/209308325-c12a35de-3735-4672-ae4f-a8af000974bc.png)

**Comment by karminski** [comment]
@ljh19930603 你好，我成功复现了场景，这是一个BUG，我们已经正在处理了。待修复后反馈。
