### ISSUE TITLE
The option to select a component is obscured

### ISSUE THREAD

**Issue by ma-pony** [illacloud/illa-builder#715]
### Description

when i added the select component on top of the container component, i found that the options were obscured

### Steps to reproduce

1. add a container component
2. add select component on top of this
3. click drop down options
4. see obscured

https://fast-try.illacloud.com/app/2955

### ILLA Builder Version

1.6.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="1858" alt="image" src="https://user-images.githubusercontent.com/38464007/209287631-beb1c06e-0362-4b07-9410-4586311629ec.png">

**Comment by AruSeito** [comment]
This is bug,we'll fix it soon

**Comment by AruSeito** [comment]
Hello, we have fixed this bug

**Comment by AruSeito** [comment]
Because it has not had recent activity. It will be closed if no further activity occurs.
