### ISSUE TITLE
maybe run error

### ISSUE THREAD

**Issue by xiasf** [illacloud/illa-builder#730]
### Description

maybe run error

### Steps to reproduce

Transformer： return data[0]  // {total: int}

{{userTotal.data.total}}

tips error: maybe run error

### ILLA Builder Version

1.2.6

### Browser

Chrome 版本 108.0.5359.99（正式版本） （64 位）

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

...

**Comment by AruSeito** [comment]
Hello,please provide more information for action info.
Such as：action type or action content

**Comment by xiasf** [comment]
![image](https://user-images.githubusercontent.com/17535757/209907328-ca46e58d-4ec4-4838-86f6-9318683082ce.png)
![image](https://user-images.githubusercontent.com/17535757/209907364-0d931724-99a1-4da1-8f11-140edf559e2e.png)

**Comment by AruSeito** [comment]
Thank you for providing effective information. We have confirmed that this is a bug and we will fix it as soon as possible.

**Comment by AruSeito** [comment]
Hello,We fixed it,you can try it again
