### ISSUE TITLE
[BUG] - After some time on editor, the entire app get frozen

### ISSUE THREAD

**Issue by sujit-baniya** [illacloud/illa-builder#749]
### Description

I'm trying to the project locally. I've installed the application and created user manually on DB. After successful login, when I try to edit a new App, it works for some minutes then everything on the app gets frozen and nothing works

### Steps to reproduce

1. Clone backend and builder locally
2. Bring up http and ws server
3. Login and try to create app

### ILLA Builder Version

latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Video: 
https://www.loom.com/share/fab6d3d699894552a3041344a0a30f5a
https://www.loom.com/share/69c6a6ede0864371b1aeeab4d580de81

**Comment by sujit-baniya** [comment]
Browser has to terminate
![image](https://user-images.githubusercontent.com/4959215/210112710-79e9e985-cb44-4a76-bf10-609a16d1c8f6.png)

**Comment by AruSeito** [comment]
We have tried to optimize it, you can try again
