### ISSUE TITLE
demo 页面注册后报错

### ISSUE THREAD

**Issue by lifesign** [illacloud/illa-builder#751]
### Description

注册 demo 页面后，报错

### Steps to reproduce

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/2189610/210190400-5b5fc118-f55a-42c9-bc03-f0c6e7fe2b69.png">

访问地址：
https://fast-try.illacloud.com/dashboard/apps

### ILLA Builder Version

最新版本

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by mhgd3250905** [comment]
me too

**Comment by AruSeito** [comment]
Plz try again,We have fixed
