### ISSUE TITLE
windows 无法运行

### ISSUE THREAD

**Issue by MarshalT** [illacloud/illa-builder#754]
### Description

第一使用

### Steps to reproduce

C:\Users\prm\Downloads\illa-x86_64-win\illa-x86_64-win>illa deploy --self
 Running a self-hosted installation...
 No running docker found.
 Please check the status of docker.

### ILLA Builder Version

1.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

C:\Users\prm\Downloads\illa-x86_64-win\illa-x86_64-win>illa deploy --self
 Running a self-hosted installation...
 No running docker found.
 Please check the status of docker.

**Comment by karminski** [comment]
@MarshalT hi, 运行环境需要docker, 请安装docker: https://www.docker.com/products/docker-desktop/

**Comment by karminski** [comment]
Issue closed due to no feedback over 5 days.
