### ISSUE TITLE
"Unhandled Thrown Error!" right after login Live demo site

### ISSUE THREAD

**Issue by Lan-Phan** [illacloud/illa-builder#756]
### Description

When I login live demo site, I got "unhandled thrown error" issue

### Steps to reproduce

See this attached image

<img width="1013" alt="Screen Shot 2023-01-03 at 8 55 07 AM" src="https://user-images.githubusercontent.com/106818620/210291113-6635743c-71af-4a85-bcaa-49761f795cbd.png">

### ILLA Builder Version

latest version on live demo site

### Browser

Chrome 104.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by AruSeito** [comment]
Plz try again,We have fixed

**Comment by Lan-Phan** [comment]
it's ok now, thanks
