### ISSUE TITLE
mysql点击运行，查询成功后的弹窗不显示

### ISSUE THREAD

**Issue by qvbepgss1** [illacloud/illa-builder#771]
### Description

mysql中点击运行没有弹框显示查询的结果

### Steps to reproduce

1. 新建mysql的action;
2. 查询：SELECT user from mysql.user;
3. 点击保存，点击运行；
4. 没有显示查询的结果；
5. 点击两次运行，会显示查询的结果；

### ILLA Builder Version

1.0.0

### Browser

Google Chrome 108.0.5359.99

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

Server version: 8.0.31 MySQL Community Server - GPL

**Comment by AruSeito** [comment]
感谢您的反馈，我们目前无法复现该问题，能麻烦您提供个操作视频或提供个您已经在我们 demo 环境创建好的 appID 吗？

**Comment by qiujiahong** [comment]
1. 下载本地部署
```
git clone https://github.com/illacloud/deploy-illa-manually.git
cd deploy-illa-manually/docker 
./scripts/run-official-image.sh
```
2.初始化数据库
```sql
drop table if exists `student`;
create table `student`(
    id int(11) primary key auto_increment,
    name varchar(20) ,
    tall int(11)
);

insert into student(name,tall) values ('张三',170),
                                    ('李四',165);

```

3、访问localhost登录
4、创建应用，拖动table组件到页面
5、创建action 
![image](https://user-images.githubusercontent.com/3654923/212353853-3b908321-072b-491e-894e-cbe05e66a44c.png)
6、点击table配置 data source为 {{mysql1.data}}
7、编辑页面能够看到数据
![image](https://user-images.githubusercontent.com/3654923/212354172-51efb0b1-a23f-471a-8261-288c821791b5.png)
**8、deploy页面没有数据**
![image](https://user-images.githubusercontent.com/3654923/212354228-9ab40df4-22bb-4f67-99f3-7d08c34fefcf.png)

**Comment by AruSeito** [comment]
> 1. 下载本地部署
> 
> ```
> 
> git clone https://github.com/illacloud/deploy-illa-manually.git
> 
> cd deploy-illa-manually/docker 
> 
> ./scripts/run-official-image.sh
> 
> ```
> 
> 2.初始化数据库
> 
> ```sql
> 
> drop table if exists `student`;
> 
> create table `student`(
> 
>     id int(11) primary key auto_increment,
> 
>     name varchar(20) ,
> 
>     tall int(11)
> 
> );
> 
> 
> 
> insert into student(name,tall) values ('张三',170),
> 
>                                     ('李四',165);
> 
> 
> 
> ```
> 
> 
> 
> 3、访问localhost登录
> 
> 4、创建应用，拖动table组件到页面
> 
> 5、创建action 
> 
> ![image](https://user-images.githubusercontent.com/3654923/212353853-3b908321-072b-491e-894e-cbe05e66a44c.png)
> 
> 6、点击table配置 data source为 {{mysql1.data}}
> 
> 7、编辑页面能够看到数据
> 
> ![image](https://user-images.githubusercontent.com/3654923/212354172-51efb0b1-a23f-471a-8261-288c821791b5.png)
> 
> **8、deploy页面没有数据**
> 
> ![image](https://user-images.githubusercontent.com/3654923/212354228-9ab40df4-22bb-4f67-99f3-7d08c34fefcf.png)
> 
> 
> 
> 

您好，感谢您的反馈。我们已经定位了bug所在，我们会在近期进行修复
