### ISSUE TITLE
组件的页面栏，文字”默认视图“换行了显示的不够友好

### ISSUE THREAD

**Issue by qvbepgss1** [illacloud/illa-builder#772]
### Description

组件的页面栏，文字”默认视图“换行了显示的不够友好

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Builder Version

1.7.3

### Browser

Google Chrome 108.0.5359.99

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by qvbepgss1** [comment]
2560*1920

**Comment by AruSeito** [comment]
您好，方便提供个示意图吗？
