### ISSUE TITLE
[feature] dark mode UI

### ISSUE THREAD

**Issue by c-nv-s** [illacloud/illa-builder#794]
### Description

As a developer I would like to be able to use Illa builder for extended periods in low light level conditions without succumbing to eye strain from a bright UI

### Steps to reproduce

1. use the UI builder in an environment with low light levels

### ILLA Builder Version

docker image id 5f6d717fefc0

### Browser

n/a

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Additional Information

none

**Comment by wenzhuo2022** [comment]
Thanks for your feedback. We are still improving the basic features such as components and resources at this stage.  Maybe we will support dark mode after these features are completed.
