### ISSUE TITLE
Feedback when no records found from DB.

### ISSUE THREAD

**Issue by hchen98** [illacloud/illa-builder#806]
### Description

If I query a record that's not in my DB. How do I make feedback to the user?

### ILLA Builder Version

1.7.8

**Comment by AruSeito** [comment]
Hello, when the data returns , you can call the success event in the eventHandler to display the message.
![image](https://user-images.githubusercontent.com/41471697/212449178-3d639a7c-6a6f-47e7-b6f4-ac143eccbc20.png)
you can write {{restapi1.data.length === 0 }} or {{restapi1.data}}
But now there are some known problems. When calling own data, errors will occur. We are trying to fix this bug.
