### ISSUE TITLE
对table字段位置做的调整，preview时有效，但deploy时没有生效

### ISSUE THREAD

**Issue by redqiang2023** [illacloud/illa-builder#845]
### Description

当我试图调整table的字段顺序时，我希望生效，但deploy的结果显示设置没有被保存。

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Builder Version

1.2.6

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![微信图片_20230119110543](https://user-images.githubusercontent.com/123042297/213346008-96fedb29-d4c1-461b-974f-941ec5667fdb.png)
没有办法对table字段调整生效。

**Comment by echoxyc** [comment]
您好，目前该问题已修复，您可以再次尝试。如果再次遇到问题，欢迎您创建新的 Issue进行反馈。
